### ISSUE TITLE
The type 'List<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Collections,

### ISSUE THREAD

**Issue by hussein-khamis** [adoconnection/RazorEngineCore#72]
```
        public string GenerateTemplate(XYZ Model, string templateName)
        {
            string templateText = ReadTemplate(templateName);

            IRazorEngineCompiledTemplate<RazorEngineTemplateBase<XYZ>> template = 
                _razorEngine.Compile<RazorEngineTemplateBase<XYZ>> (templateText);

            string result = template.Run(instance =>
            {
                instance.Model = Model;
            });

            return result;

        }
```

Hello, worked fine with normal models, but with this XYZ model, it is not working and showing me the following error:
RazorEngineCore.RazorEngineCompilationException
  HResult=0x80131500
  Source=RazorEngineCore
  StackTrace:
   at RazorEngineCore.RazorEngine.CreateAndCompileToStream(String templateSource, RazorEngineCompilationOptions options)
   at RazorEngineCore.RazorEngine.Compile[T](String content, Action`1 builderAction)
   at RazorEngineHelper.GenerateTemplate(XYZ Model, String templateName) in C:\...\RazorEngineHelper.cs:line 27

Thank you.

**Comment by adoconnection** [comment]
Hi, can you please post console app example to reproduce this exception?

system.collections is referenced by default so there is something else.

**Comment by kemmis** [comment]
In case anyone has this issue, adding the reference this way worked for me:

`builder.AddAssemblyReference(Assembly.Load("System.Collections"));`
